spring.application.name=mysticalObject
spring.datasource.url=jdbc:postgresql:///postgres?cloudSqlInstance=mysticalobjectemporium-444521:europe-west10:moe-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=nmGH1edagcYQjQyFGkb0wJybjXEgK1e3l6EkB7aWcFQ=
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
server.port=${PORT:8080}
server.address=0.0.0.0
# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://mystical-object-frontend-wgfrgx7wda-uc.a.run.app,https://mystical-object-frontend-268399530713.us-central1.run.app}
# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
# Google Cloud Storage
google.cloud.storage.bucket-name=mysticalobjectemporium