spring.application.name=mysticalObject
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=osman
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=nmGH1edagcYQjQyFGkb0wJybjXEgK1e3l6EkB7aWcFQ=
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
google.cloud.storage.bucket-name=mysticalobjectemporium
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.cloud.gcp.credentials.location=classpath:mysticalobjectemporium-444521-88fda94ddf96.json
spring.cloud.gcp.project-id=mysticalobjectemporium-444521
gcp.bucket.name=mysticalobjectemporium
# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.probes.enabled=true
